# Generated by Django 3.0.5 on 2020-11-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField(default=0)),
                ('type', models.CharField(default='', max_length=7)),
                ('title', models.CharField(default='', max_length=100)),
                ('director', models.CharField(default='', max_length=200)),
                ('cast', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('date_added', models.DateField()),
                ('release_year', models.SmallIntegerField()),
                ('rating', models.CharField(default='', max_length=200)),
                ('duration', models.SmallIntegerField()),
                ('listed_in', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
